export default {
    "success":"true",
    "data":{
        "memes":[
            {
                "id":"1",
                "name":"afreen",
                "url":"https://tse4.mm.bing.net/th?id=OIP.Ix6XjMbuCvoq3EQNgJoyEQHaFj&pid=Api&P=0&w=240&h=180",
                "width":"1200",
                "height":"1200",
                 "box-count":2
            },
            {
                "id":"2",
                "name":"afreen2",
                "url":"https://imaging.nikon.com/lineup/dslr/df/img/sample/img_01_l.jpg",
                "width":"1200",
                "height":"1200",
                 "box-count":3
            },
            {
                "id":"3",
                "name":"afreen3",
                "url":"https://cdn.vox-cdn.com/thumbor/L2_PcWH2v3bHP9nxbfkMu53QUKY=/0x63:640x423/1600x900/cdn.vox-cdn.com/assets/1892661/bing_full_screen_mode_640.jpg",
                "width":"1200",
                "height":"1200",
                 "box-count":4
            },
            {
                "id":"4",
                "name":"afreen5",
                "url":"https://alanmajchrowicz.com/wp-content/uploads/2019/01/glacier_peak_image_lake_58240.jpg",
                "width":"1200",
                "height":"1200",
                 "box-count":5
            },
            {
                "id":"5",
                "name":"afreen",
                "url":"http://cdn.thinglink.me/api/image/479353026285404161/1024/10/scaletowidth/0/0/1/1/false/true?wait=true",
                "width":"1200",
                "height":"1200",
                 "box-count":6
            },
            {
                "id":"6",
                "name":"afreen77",
                "url":"https://tse4.mm.bing.net/th?id=OIP.0ci0fY7W9l0_chsZVVUgLAHaFj&pid=Api&P=0&w=252&h=189",
                "width":"1200",
                "height":"1200",
                 "box-count":7
            },
            {
                "id":"7",
                "name":"afrewwen",
                "url":"https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto/gigs/125329317/original/a12d39618eaca59331ee3e0533882fbc99dcba4b/send-my-beautiful-image-jpeg-file-4mb-file-size.jpg",
                "width":"1200",
                "height":"1200",
                 "box-count":8
            },
            {
                "id":"8",
                "name":"afrqqeen",
                "url":"https://www.creavea.com/produits/82320-l/image-3d-divers-zen-n2-30-x-30-cm-l.jpg",
                "width":"1200",
                "height":"1200",
                 "box-count":9
            },
            {
                "id":"9",
                "name":"aaaafreen",
                "url":"https://www.asicentral.com/media/20479/scottcolumnfig4-800.jpg",
                "width":"1200",
                "height":"1200",
                 "box-count":10
            },
            {
                "id":"10",
                "name":"afransaieen",
                "url":"https://nssdc.gsfc.nasa.gov/image/solar/eit_sl_171.jpg",
                "width":"1200",
                "height":"1200",
                 "box-count":11
            },
            {
                "id":"11",
                "name":"afrewerwen",
                "url":"https://cdn55.picsart.com/168598511001201.jpeg",
                "width":"1200",
                "height":"1200",
                 "box-count":12
            },
            {
                "id":"12",
                "name":"afreenases",
                "url":"https://liberalarts.iupui.edu/images/faculty-staff/zoom-virtual-backgrounds/Circle-Center-Zoom.png",
                "width":"1200",
                "height":"1200",
                 "box-count":13
            }
        ]
    }
}